#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

echo "Transferring file to $server_ip..."

# Use scp to transfer file to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

echo "File transferred successfully!
